import './globals.css'
import Header from './components/Header'
import { Montserrat } from 'next/font/google'
import { ReactNode } from 'react'

// const inter = Comic_Neue({ subsets: ['latin'] })
const inter = Montserrat({
  subsets: ['latin'],
  // weight: '400',
})

export const metadata = {
  title: 'Redux Contabilidade',
  description: 'Generated by create next app',
  favicon: '/src/app/favicon.ico',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <Header />
        <main className="min-h-screeen flex w-full flex-1 items-center justify-center">
          {children}
        </main>
      </body>
    </html>
  )
}
